version: '2'
services:
  db:
    image: postgres

  api:
    build: .
    environment:
      MIX_ENV: dev
    volumes:
      - .:/marketplace
    ports:
      - "4000:4000"
    depends_on:
      - db
